filter:
    excluded_paths:
        - 'vendor/*'
tools:
    external_code_coverage:
        enabled: true
        timeout: 600
    php_cpd:
        enabled: true
        excluded_dirs:
            - 'vendor'
    php_pdepend:
        enabled: true
        excluded_dirs:
            - 'vendor'
    php_loc:
        enabled: true
        excluded_dirs:
            - 'vendor'
    php_mess_detector: true
    php_analyzer: true
    sensiolabs_security_checker: true

before_commands:
    - 'composer update --dev --no-interaction'